### ISSUE TITLE
Any plans to register DarkMode as an official package in the Julia registry?

### ISSUE THREAD

**Issue by ali-ramadhan** [Pocket-titan/DarkMode#3]
Loving the dark theme! Just wondering if there are any plans to register this as a package?

**Comment by Pocket-titan** [comment]
Thanks a lot 😊! At the moment, not really. The problem is that this package really only makes sense inside a Pluto environment, so putting it in the general Julia registry feels wrong: it won't do anyhting when imported in a regular Julia shell. Besides, the idea is that this eventually becomes a part of Pluto itself - then it won't even need to exist on its own at all 😄
